apiVersion: v1
kind: Service
metadata:
  name: legal-api-service
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    app: legal-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
